import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd(),source=path.join(root,'content'),domain='https://endlessweep.com';
const existing=['','game-modes','daily-minesweeper','zen-minesweeper','custom-minesweeper','how-to-play-minesweeper','minesweeper-strategy','minesweeper-patterns','minesweeper-guessing','minesweeper-controls','minesweeper-statistics'];
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function inline(s){return escape(s).replace(/\[([^\]]+)\]\((\/[^)]+)\)/g,'<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>')}
function markdown(text){const out=[];let list=null;const close=()=>{if(list){out.push(`</${list}>`);list=null}};for(const raw of text.trim().split('\n')){const line=raw.trim();if(!line){close();continue}if(line.startsWith('## ')){close();out.push(`<h2>${inline(line.slice(3))}</h2>`)}else if(line.startsWith('### ')){close();out.push(`<h3>${inline(line.slice(4))}</h3>`)}else if(/^[-*] /.test(line)){if(list!=='ul'){close();list='ul';out.push('<ul>')}out.push(`<li>${inline(line.slice(2))}</li>`)}else if(/^\d+\. /.test(line)){if(list!=='ol'){close();list='ol';out.push('<ol>')}out.push(`<li>${inline(line.replace(/^\d+\. /,''))}</li>`)}else if(line.startsWith('> ')){close();out.push(`<p class="note">${inline(line.slice(2))}</p>`)}else{close();out.push(`<p>${inline(line)}</p>`)}}close();return out.join('\n')}
function read(file){const text=fs.readFileSync(file,'utf8'),match=text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);if(!match)throw Error(`${file}: missing front matter`);const meta={};for(const line of match[1].split('\n')){const i=line.indexOf(':');if(i<1)throw Error(`${file}: invalid front matter`);meta[line.slice(0,i).trim()]=line.slice(i+1).trim()}for(const key of ['title','description','slug','heading','summary'])if(!meta[key])throw Error(`${file}: missing ${key}`);if(!/^[a-z0-9-]+$/.test(meta.slug))throw Error(`${file}: invalid slug`);return{...meta,body:markdown(match[2])}}
const css=`:root{--ink:#182230;--muted:#64748b;--line:#d8e0ea;--blue:#2563eb;--panel:#fff}*{box-sizing:border-box}body{margin:0;background:#eef3f8;color:var(--ink);font:16px/1.68 system-ui,-apple-system,"Segoe UI",sans-serif}main{width:min(100% - 28px,820px);margin:auto;padding:30px 0 52px}header,footer{text-align:center}h1{margin:0 0 8px;font-size:clamp(28px,6vw,44px);line-height:1.15}header p,footer{color:var(--muted)}nav{display:flex;flex-wrap:wrap;justify-content:center;gap:14px;margin:18px 0}a{color:var(--blue);font-weight:700;text-decoration:none}.cta{display:inline-block;padding:10px 15px;border-radius:7px;background:var(--blue);color:#fff}.content{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:24px}h2{margin:28px 0 7px;font-size:23px}h2:first-child{margin-top:0}h3{margin:20px 0 5px}ul,ol{padding-left:22px}.note{padding:12px 14px;background:#f1f5f9;border-left:3px solid var(--blue)}code{padding:2px 5px;background:#f1f5f9;border-radius:4px}@media(max-width:520px){.content{padding:18px}}`;
const articles=fs.readdirSync(source).filter(x=>x.endsWith('.md')).sort().map(x=>read(path.join(source,x)));
const nav='<nav><a class="cta" href="/">Play Minesweeper</a><a href="/minesweeper-guides/">All Guides</a><a href="/minesweeper-strategy/">Strategy</a><a href="/minesweeper-patterns/">Patterns</a></nav>';
for(const article of articles){const url=`${domain}/${article.slug}/`,json=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:article.heading,description:article.description,inLanguage:'en',mainEntityOfPage:{'@type':'WebPage','@id':url}});const html=`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${escape(article.description)}"><link rel="canonical" href="${url}"><title>${escape(article.title)}</title><style>${css}</style></head><body><main><header><h1>${escape(article.heading)}</h1><p>${escape(article.summary)}</p>${nav}</header><article class="content">${article.body}</article><footer><p>Practice what you learned on a real board.</p><a class="cta" href="/">Play Free Minesweeper</a>${nav}</footer></main><script type="application/ld+json">${json}</script></body></html>\n`;fs.mkdirSync(path.join(root,article.slug),{recursive:true});fs.writeFileSync(path.join(root,article.slug,'index.html'),html)}
const cards=articles.map(a=>`<li><a href="/${a.slug}/">${escape(a.heading)}</a><p>${escape(a.summary)}</p></li>`).join('');const guideUrl=`${domain}/minesweeper-guides/`;const guideJson=JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage',name:'Minesweeper Guides',url:guideUrl,inLanguage:'en'});const guide=`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Minesweeper guides covering rules, controls, patterns, probability, speed, difficulty, and common mistakes."><link rel="canonical" href="${guideUrl}"><title>Minesweeper Guides: Learn, Solve and Improve</title><style>${css}.guides{list-style:none;padding:0}.guides li{padding:16px 0;border-bottom:1px solid var(--line)}.guides p{margin:4px 0;color:var(--muted)}</style></head><body><main><header><h1>Minesweeper Guides</h1><p>Learn the rules, solve common positions, and improve your play.</p>${nav}</header><article class="content"><ul class="guides">${cards}</ul></article><footer><a class="cta" href="/">Play Free Minesweeper</a></footer></main><script type="application/ld+json">${guideJson}</script></body></html>\n`;fs.mkdirSync(path.join(root,'minesweeper-guides'),{recursive:true});fs.writeFileSync(path.join(root,'minesweeper-guides','index.html'),guide);
const urls=[...existing,'minesweeper-guides',...articles.map(a=>a.slug)];fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(x=>`  <url><loc>${domain}/${x?`${x}/`:''}</loc></url>`).join('\n')}\n</urlset>\n`);console.log(`Built ${articles.length} articles and sitemap.xml`);
